### ISSUE TITLE
Refus still executes in rails console & rake tasks

### ISSUE THREAD

**Issue by mikebaldry** [gottfrois/dashing-rails#15]
Very annoyingly comes up with a bunch of AR logs, etc etc every 30 seconds :)

Would be really cool if the schedule didn't start on rails console or during rake task execution..

**Comment by holgersindbaek** [comment]
@gottfrois @brightbits  This one is really annoying. Has anyone been able to do anything about it?

**Comment by holgersindbaek** [comment]
I ended up stopping the scheduler if running from rake task:

Dashing.scheduler.shutdown if File.basename($0) == 'rake'

**Comment by gottfrois** [comment]
Like I said in 2013, not much I can do about it here :(
