### ISSUE TITLE
Is the Graph widget working?

### ISSUE THREAD

**Issue by diegoqueiroz5a** [gottfrois/dashing-rails#66]
I'm trying to make the Graph widget work, but it only shows the last value as text, not the graph in background.

I grabbed the sample code from dashing to send data to the widget:

points = []
(1..10).each do |i|
  points << { x: i, y: rand(50) }
end
last_x = points.last[:x]

Dashing.scheduler.every '2s' do
  points.shift
  last_x += 1
  points << { x: last_x, y: rand(50) }
  Dashing.send_event('convergence', value: points)
end

What am I doing wrong?

**Comment by gottfrois** [comment]
you are talking about this one ? http://d.pr/i/1h7SU

**Comment by diegoqueiroz5a** [comment]
Sorry, I posted the title before the body

**Comment by diegoqueiroz5a** [comment]
Yeah. This one.

**Comment by gottfrois** [comment]
I believe so yes, long time I did use it though

**Comment by diegoqueiroz5a** [comment]
Where can I take a look on the Coffeescript code of this widget?

**Comment by gottfrois** [comment]
graph is defined here https://github.com/gottfrois/dashing-rails/blob/master/vendor/assets/javascripts/dashing/default_widgets/graph.coffee

**Comment by joseschmidt** [comment]
I can't get the chart to work either, any tip?

**Comment by joseschmidt** [comment]
On the `graph.coffee` file the `@graph` variable is undefined for some reason.

    onData: (data) ->
      console.log('onData - graph:'+@graph) 
      if @graph
        @graph.series[0].data = data.points
        @graph.render()

Javascript throws:

      onData - graph:undefined

**Comment by gottfrois** [comment]
Should be fixed in `v2.4.1`
