### ISSUE TITLE
Using -d on server start not working

### ISSUE THREAD

**Issue by joseschmidt** [gottfrois/dashing-rails#69]
I can run the application without any issues without the -d, however as soon as i put -d i get the widgets with no data. I added console.log in javascript to listen to onData event but i get nothing logged when using the -d option either. 

the application log shows that the request is reaching the server

**Comment by gottfrois** [comment]
sorry but i'm not familiar with what you call the `-d` option. Can you please explain what this is?

Nevertheless, running the puma server with a simple `rails s` command should work just fine.

**Comment by joseschmidt** [comment]
my bad sorry i mean when doing like `rails s -d`

**Comment by joseschmidt** [comment]
And you are right about puma, i had to start a separated puma server, don't know much about it so i did `bundle exec puma -t 0:5 -d` and afterwards i was able to do the `rails s -d` with no problem!

**Comment by gottfrois** [comment]
ok great :)
