### ISSUE TITLE
Rufus scheduler just stops: uninitialized constant SCHEDULER

### ISSUE THREAD

**Issue by RBdevelop** [gottfrois/dashing-rails#70]
After running seemingly fine for few hours the jobs stop running. After restarting the servers I keep getting : 

app/jobs/buzzwords.rb:4:in `<top (required)>': uninitialized constant SCHEDULER (NameError) 

and can't restart the server without removing the jobs files. 

I looked up the rufus-scheduler docs but there is no consenus on solution . It appears Rufus can intermittently fail. 

That said do you recommend a different scheduling gem that will work with Dashing-Rails?

**Comment by gottfrois** [comment]
That's a shame :(

You can in theory use whatever you like as long as events end-up in redis somehow. The easiest is to use dashing-rails API:

```ruby
Dashing.send_event('karma', { current: rand(1000) })
```
