### ISSUE TITLE
Dynamic Dashboard Layout

### ISSUE THREAD

**Issue by LetologyGitHub** [gottfrois/dashing-rails#73]
Firstly thanks for all this work it's great. 

Would it be possible to do the following, at the moment 

server:3000/dashing/ => dashing/dashboards/sample.html.erb

How can I get to,

server:3000/dashing/:dashboard => controller or view which could take that :dashboard variable and then generate the view dynamically? ie you could change the dashboard by passing a variable  rather than matching the filename

I would appreciate any help/direction you can give me.

**Comment by gottfrois** [comment]
Have you try just doing:

`http://localhost:3000/dashing/dashboards/foo`

and have the `foo` dashboard define in `app/views/dashing/dashboards/foo.html.erb`

**Comment by LetologyGitHub** [comment]
Yep. I worked it out. my Ruby/Rails skills are limited, so although I know
what I want to do and can build the backend/DB side, I am little slow with
scopes and passing around variables.

On 3 May 2015 at 14:02, Pierre-Louis Gottfrois <notifications@github.com>
wrote:

> Have you try just doing:
>
> http://localhost:3000/dashing/dashboards/foo
>
> and have the foo dashboard define in
> app/views/dashing/dashboards/foo.html.erb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gottfrois/dashing-rails/issues/73#issuecomment-98477994>
> .
>



-- 

Jagdeep Bhaura
Director

email : jagdeep.bhaura@jbhaura.com

Mobile : +44 (0) 7973 786 164 | + 1(646) 867 3039
Office  : +44 (0) 20 3397 4574
Fax     : +44 (0) 330 223 0524

Skype: bhaurajs

W: http://www.jbhaura.com

A: 27 Old Gloucester Street, London, WC1N 3AX



*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you are not the named addressee please do not disseminate, distribute or
copy this e-mail. Please notify the sender immediately by e-mail if you
have received this e-mail by mistake and delete this e-mail from your
system.JB Squared Ltd. is a limited company registered in England and
Wales. Registered number: 7260820. Registered office: 27 Old Gloucester
Street, London, WC1N 3AX*

**Comment by gottfrois** [comment]
No worries :)
