### ISSUE TITLE
Dynamically generate a widget

### ISSUE THREAD

**Issue by digitalWestie** [gottfrois/dashing-rails#75]
I'm trying to dynamically add a widget to the dashboard.  

So far I've got Javascript that adds html for the new widget, but it still doesn't show up. I'm guessing it needs to be added to the list of widgets observed by Dashing JS? In which case, is there a way to reload the list of widgets?

**Comment by gottfrois** [comment]
Widgets are loaded regarding their path on the file system:
https://github.com/gottfrois/dashing-rails/blob/master/app/controllers/dashing/widgets_controller.rb#L11

Can you give me more details on how you generate your widget?

**Comment by digitalWestie** [comment]
I should be a bit clearer about what I'm trying to achieve. I a working dashboard. What I'd like to do is give the user the option of clicking on a button and it generating a new widget. For example I have a widget showing temperature in a line graph widget. I'd like the user to be able to hit a button, and have another widget appear, but this time with a bar graph.

**Comment by gottfrois** [comment]
ok, your widget must exists in a html file in your project. Then try to send an Ajax request to hit this action https://github.com/gottfrois/dashing-rails/blob/master/app/controllers/dashing/widgets_controller.rb#L11

This is basically what's happening when you load the default dashboard. Take a look at the developer console

**Comment by digitalWestie** [comment]
Ahah, that's really useful thanks for your help! :)
