### ISSUE TITLE
How to add  Authentication? 

### ISSUE THREAD

**Issue by veetase** [gottfrois/dashing-rails#76]
Because I don't want everyone to see it.

**Comment by gottfrois** [comment]
You have those 2 options in the config initializer https://github.com/gottfrois/dashing-rails/blob/master/lib/generators/templates/initializer.rb#L50-L57

Basically you need to generate a auth_token and then pass it as a parameter `params[:auth_token]` in order to access the dashboards

**Comment by veetase** [comment]
Thank you, I finally made it by another way, I added a contraint on the route.
