### ISSUE TITLE
Widgets display current and old data

### ISSUE THREAD

**Issue by hanyelbana** [gottfrois/dashing-rails#78]
First, Thanks for great gem.

With each sending for data by send_event, widget display current data for 2 seconds and then display old data.

It should display only current data as I think!?

I have removed rand(100) before redis-server start and send only one number and change it manual to test.

Thanks

**Comment by mitoyarzun** [comment]
Check if you have another spring process running with ```ps aux | grep spring``` and then kill it.

**Comment by gottfrois** [comment]
Closing. Feel free to re-open in case it's a dashing-rails issue.

**Comment by alexsheehan1** [comment]
i'm also having this issue. it seems to be caching old versions of the sent data somewhere. but ive disabled caching (tried to at least). not sure whats going on exactly. ill keep poking around and hopefully figure it out
