### ISSUE TITLE
Dashing rails assets is not working in production evn.

### ISSUE THREAD

**Issue by AfzalMasood11** [gottfrois/dashing-rails#81]
I am using rails 4.2.0 and ruby 2.2.0.
I am trying to change app environment development to production, at my local machine. but in production dashboard assets does not work.
In development :
![development](https://cloud.githubusercontent.com/assets/3656279/10883887/a7ae13d8-8196-11e5-979f-47527a55310d.png)

where as in production:
![production](https://cloud.githubusercontent.com/assets/3656279/10883324/0ee7f3e2-8193-11e5-8fb4-a13019e89d68.png)

Here are my production.rb settings:
<pre>
config.serve_static_files = true
config.assets.js_compressor = Uglifier.new(mangle: false)
config.assets.compile = false
config.assets.digest = true
</pre>

I had run rake assets:precompile RAILS_ENV="production"

I noticed that in web console I am getting these error:
<pre>
Uncaught TypeError: $(...).jQCloud is not a function
Uncaught ReferenceError: Highcharts is not defined
</pre>
Although I have required these above js in dashing/widgets/index.js
<pre>
//= require_tree .
//= require highcharts/highstock
//= require highcharts/highcharts-more
//= require highcharts/modules/exporting
//= require jquery-ui
//= require jqcloud
</pre>

I am using 'lazy_high_charts' and 'jqcloud-rails' gems.

How to fix this layout issue!
Any Help!!!!

**Comment by gottfrois** [comment]
Did you try adding them to asset precompile?

**Comment by AfzalMasood11** [comment]
yes, As I mentioned that I had run: rake assets:precompile RAILS_ENV="production"

**Comment by gottfrois** [comment]
not talking about the rake task :) did you explicitely added the libs in the asset path?

```
config.assets.precompile += %w(highcharts/highstock ...)
```

**Comment by AfzalMasood11** [comment]
yes, I forgot to mention that. I added them in initializers/assets.rb like this:
<pre>
Rails.application.config.assets.precompile +=  ["higcharts/*"]
Rails.application.config.assets.precompile +=  ["higcharts/highstock", "highcharts/highcharts-more", "highcharts/modules/exporting"]
Rails.application.config.assets.precompile +=  ["jqcloud.js", "jqcloud.css"]
</pre>

**Comment by timurvafin** [comment]
I've described issue in this comment https://github.com/gottfrois/dashing-rails/pull/79#issuecomment-154085283

That pull request should help issue completely.

**Comment by gottfrois** [comment]
Closing, let me know if it still does not work.

**Comment by AfzalMasood11** [comment]
thanks @timurvafin and @gottfrois It works for me, I just had to update the dashing_rails gem from 2.4.4 to 2.4.5. :)
