### ISSUE TITLE
Load data when site loads

### ISSUE THREAD

**Issue by holgersindbaek** [gottfrois/dashing-rails#84]
Is this possible?

We have one dashboard in the office and I've set it to run the jobs every 5 minutes. We need to be able to go into the website from home and see the data though. How can I make the data load as soon as you go into the website, so I don't have to wait 5 minutes before I can see the data?

**Comment by gottfrois** [comment]
When someone loads the dashboard in their browser, all widgets will automatically receive the last values that the job server fetched -- you shouldn't need to tell the job to re-run.

Is this behaviour not showing for you?

You might want to look at https://github.com/Shopify/dashing issues if this is the case.

**Comment by holgersindbaek** [comment]
No... I have to wait until the next push occurs. Is it the "first_in: 0" that should make sure it runs when someone enters the site? Or does the latest information get saved somewhere somehow?!

**Comment by gottfrois** [comment]
I don't think it's `first_in` option. It's just there to tell the job to starts right away.

Might be an issue on frond-end side. I would need to upgrade to last version maybe.

**Comment by holgersindbaek** [comment]
It's weird. I ended up making a gross hack. I call a function from the main dashing jQuery file, that runs all the jobs again. So the jobs get run now on load. Couldn't get it to work otherwise.

**Comment by gottfrois** [comment]
Upgrading to dashing-rails 2.5.0 should now fix your issue
