### ISSUE TITLE
Connection Errors

### ISSUE THREAD

**Issue by alonhartal** [gottfrois/dashing-rails#85]
I'm using dashing-rails on heroku following https://github.com/gottfrois/dashing-rails/wiki/Run-Dashing-Rails-on-Heroku.
after few seconds (which everything works fine - getting events and metrics are displayed), the connection is closed and I stop receiving events.

![console](https://cloud.githubusercontent.com/assets/8341789/13034232/ac52dac4-d338-11e5-99f8-aa4a97c002a0.png)

**Comment by alonhartal** [comment]
these are the logs:
`016-02-14T15:01:22.512141+00:00 heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=GET path="/dashing/events" host=cheetah-dashboard.herokuapp.com request_id=cf29f31e-e2ec-4665-acad-fbf9b2819ebf fwd="84.228.69.45" dyno=web.1 connect=0ms service=80370ms status=499 bytes=909
2016-02-14T15:02:17.512327+00:00 heroku[router]: at=error code=H15 desc="Idle connection" method=GET path="/dashing/events" host=cheetah-dashboard.herokuapp.com request_id=621b053c-1abe-40f1-98aa-063ed7eebeac fwd="84.228.69.45" dyno=web.1 connect=0ms service=71816ms status=503 bytes=972`

**Comment by gottfrois** [comment]
It's probably cause by your heroku dyno going to sleep. Is it a paid dyno?

**Comment by alonhartal** [comment]
It's a paid Dyno

**Comment by gottfrois** [comment]
Not sure what's wrong but this is interesting https://devcenter.heroku.com/articles/request-timeout#long-polling-and-streaming-responses

**Comment by alonhartal** [comment]
I'll try to adding a heartbeat job and let you know if that works.

another question - when I reload browser the data is cleared until next update. it shouldn't be saved on redis?

**Comment by gottfrois** [comment]
You are probably having the same issue than this one https://github.com/gottfrois/dashing-rails/issues/84

**Comment by alonhartal** [comment]
looks like the heartbeat solves the first issue. thanks?
yes we have the same issue - any idea to solution?

**Comment by gottfrois** [comment]
Not really unfortunatelly :( Best guess is I should try upgrading JS with dashing source files.

**Comment by alonhartal** [comment]
I'm debugging on my local and I don't see redis stores the data (only publish events). so where is the data stored?

**Comment by gottfrois** [comment]
data is not meant to be persisted for a long time. JS widgets should be able to pick up last value when dashboard loads, but maybe i missed something and the sinatra version does something special here.

If you find anything let me know. I don't have time right now to dig into this :(

**Comment by alonhartal** [comment]
Thanks. will keep you updated on this.

**Comment by scambra** [comment]
I checked sinatra code and it returns latest values when events connection starts:
```ruby
get '/events', provides: 'text/event-stream' do
  protected!
  response.headers['X-Accel-Buffering'] = 'no' # Disable buffering for nginx
  stream :keep_open do |out|
    settings.connections << out
    out << latest_events
    out.callback { settings.connections.delete(out) }
  end
end
```

**out << latest_events** will send event for latest values

latest_events get events from a hash in Sinatra::Application.settings.history

**Comment by gottfrois** [comment]
Hm interesting, so this is something we should do on dashing too! Thanks for looking at this. Don't know when exactly I'll have time to implement this though.

**Comment by scambra** [comment]
I will send a pull request with an implementation using redis, I have tested and it works, really easy

**Comment by gottfrois** [comment]
That would be great, thanks :)

**Comment by alonhartal** [comment]
@scambra still not working for me. any idea? when I reload the page the values are removed from the dashboards.

**Comment by scambra** [comment]
Check if you are getting data in redis, dashing_events.latest, it's a hash
Also, check network tab in web inspector, you should get events when connection is started.

Last thing, you need scheduler update values with updated dashing-rails code at least once, becuase now Dashing.send_event use redis.hset and redis.publish, hset is needed to get latest values when refresh.

If you have different processes for web and events, you need to restart events server, so it gets latest data from redis, and process which runs scheduler, so it saves data to redis.
