### ISSUE TITLE
Add hotness as a dashing-rails default widget

### ISSUE THREAD

**Issue by Mbuckley0** [gottfrois/dashing-rails#90]
I wanted to add hotness as a default widget so you don't have to include an extra gem just for that widget. I am happy to do the work to get this included.

**Comment by gottfrois** [comment]
Thanks for the proposition but i think widgets should stay in a choose & pick solution. What bother you by adding an extra gem to bring an extra functionality?

**Comment by Mbuckley0** [comment]
No problem. The gem isn't really an issue I just considered the hotness widget more of a default widget then a custom one as it isn't reliant on an external service and only contains a css, html and js file.

**Comment by gottfrois** [comment]
You are right, I just want to mimic default widgets from dashing original repo :)
