### ISSUE TITLE
Apache2 or puma

### ISSUE THREAD

**Issue by EvertVersteeg** [gottfrois/dashing-rails#93]
My rails 4 project runs on apache2  + passender, can i use dashboard-rails to add a dashboard to my project?  (Without Puma)

**Comment by gottfrois** [comment]
As long as the server support threads you should be fine, though you'll be going off the track and will probably have to tweak things around on your side. Such as https://github.com/gottfrois/dashing-rails/blob/master/lib/dashing/railtie.rb#L21
