### ISSUE TITLE
 NoMethodError (undefined method `quit' for nil:NilClass Did you mean?  quietly):

### ISSUE THREAD

**Issue by alpha-qu** [gottfrois/dashing-rails#97]
I am using puma server and app is in development environment. After refreshing the dashboard page in browser 4-5 times, I get the mentioned error.
This is what the server says in terminal.

`Started GET "/dashing/widgets/list.html" for 127.0.0.1 at 2017-06-21 14:35:48 +0530
Processing by Dashing::WidgetsController#show as HTML
  Parameters: {"name"=>"list"}
  Rendered dashing/widgets/list.html (0.9ms)
Completed 200 OK in 6ms (Views: 5.1ms | ActiveRecord: 0.0ms)

Started GET "/dashing/widgets/text.html" for 127.0.0.1 at 2017-06-21 14:35:48 +0530
Processing by Dashing::WidgetsController#show as HTML
  Parameters: {"name"=>"text"}
  Rendered dashing/widgets/text.html (0.7ms)
Completed 200 OK in 3ms (Views: 2.2ms | ActiveRecord: 0.0ms)
Completed 500 Internal Server Error in 3002ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `quit' for nil:NilClass
Did you mean?  quietly):
  dashing-rails (2.6.1) app/controllers/dashing/events_controller.rb:19:in `ensure in index'
  dashing-rails (2.6.1) app/controllers/dashing/events_controller.rb:20:in `index'
  actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.6) lib/action_controller/metal/live.rb:278:in `block in process'

  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.2ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.3ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.2ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (26.5ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.5ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.4ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (22.9ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (1.9ms)
  Rendered /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (48.4ms)
{ 70346364373320 rufus-scheduler intercepted an error:
  70346364373320   job:
  70346364373320     Rufus::Scheduler::EveryJob "30s" {}
  70346364373320   error:
  70346364373320     70346364373320
  70346364373320     Timeout::Error
  70346364373320     Waited 3 sec
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:86:in `block (2 levels) in pop'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `loop'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `block in pop'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:77:in `synchronize'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:77:in `pop'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:89:in `checkout'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:61:in `block in with'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:131:in `with'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:143:in `method_missing'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dashing-rails-2.6.1/lib/dashing.rb:23:in `send_event'
  70346364373320       /home/deepak/Desktop/test/app/jobs/test_job.rb:65:in `block (2 levels) in <top (required)>'
  70346364373320       /home/deepak/Desktop/test/app/jobs/test_job.rb:64:in `each'
  70346364373320       /home/deepak/Desktop/test/app/jobs/test_job.rb:64:in `block in <top (required)>'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:210:in `do_call'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:254:in `trigger_now'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:296:in `block (3 levels) in start_work_thread'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:299:in `block (2 levels) in start_work_thread'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:285:in `loop'
  70346364373320       /home/deepak/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:285:in `block in start_work_thread'
  70346364373320   tz:
  70346364373320     ENV['TZ']: 
  70346364373320     Time.now: 2017-06-21 14:36:04 +0530
  70346364373320     local_tzone: #<TZInfo::TimezoneProxy: Etc/UTC>
  70346364373320   et-orbi:
  70346364373320     (etz:nil,tnz:"IST",tzid:nil,rv:"2.3.3",rp:"x86_64-linux",eov:"1.0.4",rorv:"4.2.6",astz:"UTC",debian:"Asia/Kolkata",centos:nil,osx:nil)
  70346364373320   scheduler:
  70346364373320     object_id: 47204314407900
  70346364373320     opts:
  70346364373320       {}
  70346364373320       frequency: 0.3
  70346364373320       scheduler_lock: #<Rufus::Scheduler::NullLock:0x0055dd38ace430>
  70346364373320       trigger_lock: #<Rufus::Scheduler::NullLock:0x0055dd38ace3e0>
  70346364373320     uptime: 65.82424783706665 (1m5s824)
  70346364373320     down?: false
  70346364373320     threads: 2
  70346364373320       thread: #<Thread:0x0055dd3c0d85a8>
  70346364373320       thread_key: rufus_scheduler_47204314407900
  70346364373320       work_threads: 1
  70346364373320         active: 1
  70346364373320         vacant: 0
  70346364373320         max_work_threads: 28
  70346364373320       mutexes: {}
  70346364373320     jobs: 1
  70346364373320       at_jobs: 0
  70346364373320       in_jobs: 0
  70346364373320       every_jobs: 1
  70346364373320       interval_jobs: 0
  70346364373320       cron_jobs: 0
  70346364373320     running_jobs: 1
  70346364373320     work_queue: 0
} 70346364373320 .
`

**Comment by gottfrois** [comment]
Thanks, this method seems to be gone https://github.com/gottfrois/dashing-rails/blob/master/app/controllers/dashing/events_controller.rb#L19

**Comment by gottfrois** [comment]
ah no, i missread, the redis ivar is nil, weird

**Comment by alpha-qu** [comment]
What should I do in order to remove this error? Please help as I am new to it.

**Comment by alpha-qu** [comment]
I set the ENV[RAILS_MAX_THREADS] to 30 and after 14-15 times refreshing a page, server gave an error ActionController::Live::ClientDisconnected (client disconnected).  Accoording to me, it is due to connection breakage of redis with my application server which is required by your dashing-rails and on running 'Dashing.redis' just before server gives an error I get output as *Error in Evaluation* that is why I think @redis.quit gives an error.

**Comment by alpha-qu** [comment]
I'll highly appreciate if someone could give a quick response.

**Comment by gottfrois** [comment]
what we need to know is why your redis ivar is set to nil in this controller https://github.com/gottfrois/dashing-rails/blob/master/app/controllers/dashing/events_controller.rb#L10

do you have the stack trace when you run `Dashing.redis` before it crashes?

**Comment by alpha-qu** [comment]
Stack Trace is the same as I mentioned abbove. It says NoMethodError (undefined method quit' for nil:NilClass Did you mean? quietly)

**Comment by alpha-qu** [comment]
Refreshing issue is now solved. I played around with the threads a little and debugged the issue.Thanks for your active support.
But there is one more problem, I can access only 5 dashboards at a time. In case I want to access another one, I have to close one of the opened dashboards tabs. Server says nothing but the page doesn't load.

**Comment by gottfrois** [comment]
you can increase the connection size i imagine but yeah, essentially, this is the limitation of rails action live feature. We would need to move to action cable for better real-time support.

**Comment by alpha-qu** [comment]
How to increase the connection size if you could tell me?

**Comment by gottfrois** [comment]
with `RAILS_MAX_THREADS`, it also increase the redis connection pool
