### ISSUE TITLE
Not connecting through localhost:3000

### ISSUE THREAD

**Issue by leonhatori00** [gottfrois/dashing-rails#99]
I ve got a message that it is listening on 0.0.0.0:3000, but when I connect through the browser, it does not work. 

Is there a place where I can see a log or something like that?
Thanks

**Comment by gottfrois** [comment]
Logs should appear in the console or in `logs` folder, have you look there?

**Comment by gottfrois** [comment]
Probably some mois configuration on your end, closing.
